# -*- coding: utf-8 -*-
"""APPL_Stock_Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WNr6_r6JFN_ayODno2Ic8-Sx3K97ZoYn

# ALGORITHMIC TRADING
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use("fivethirtyeight")

"""IMPORTING FILES USING COLAB"""

from google.colab import files
uploaded = files.upload()

"""READING FILES"""

df = pd.read_csv("Data_A.csv",parse_dates= True , index_col=0)
df.head()

"""INFO OF DATA"""

df.info()

"""PLOTTING THE CLOSE PRICE HISTORY"""

plt.figure(figsize=(12.2,4.5))
plt.plot(df['Close'],label ='Close')
plt.title("Close price history")
plt.xlabel("Date")
plt.xticks(rotation=45)
plt.ylabel("Price in USD")
plt.show()

"""CALCULATING AND PLOTTING THE SHORTEMA AND LONGEMA AND MACD"""

shortEMA = df.Close.ewm(span =12 , adjust =False).mean()
longEMA  = df.Close.ewm(span=26,adjust= False).mean()
MACD = shortEMA-longEMA
signal = MACD.ewm(span = 9 , adjust = False ).mean()
plt.figure(figsize=(12.2,4.5))
plt.title("MACD vs Signal Line")
plt.plot(df.index,MACD,label ='APPL MACD',color= 'red')
plt.plot(df.index,signal,label='Signal Line',color='blue')
plt.xticks(rotation=45)
plt.legend(loc='upper left')
plt.show()

"""CREATING COLUMN FOR OUTPUTS"""

df['MACD'] = MACD
df['Signal Line'] = signal
df

"""STRATEGY FOR CALCULATION"""

def buy_sell(signal):
  Buy = []
  Sell = []
  flag = -1

  for i in range(0,len(signal)):
    if signal['MACD'][i]>signal['Signal Line'][i]:
      Sell.append(np.nan)
      if flag != 1:
        Buy.append(signal['Close'][i])
        flag = 1
      else:
        Buy.append(np.nan)
    elif signal['MACD'][i]< signal['Signal Line'][i]:
      Buy.append(np.nan)
      if flag != 0:
        Sell.append(signal['Close'][i])
        flag = 0
      else:
        Sell.append(np.nan)
    else:
      Buy.append(np.nan)
      Sell.append(np.nan)
  return (Buy,Sell)

"""CREATING THE COLUMN FOR STRATEGY VALUES"""

b =buy_sell(df)
df['Buy_Signal_Price'] = b[0]
df['Sell_Signal_Price']= b[1] 
df

"""VISUALISING THE STRATEGY OUTPUT"""

plt.figure(figsize=(12.2,4.5))

plt.scatter(df.index ,df['Buy_Signal_Price'],color='green',label='buy',marker ='^',alpha=1)
plt.scatter(df.index ,df['Sell_Signal_Price'],color='red',label='sell',marker ='v',alpha=1)
plt.plot(df['Close'],label ="Close Price",alpha = 0.35)
plt.title("Close Price Buy & Sell Signals ")
plt.xticks(rotation = 45)
plt.xlabel("Date")
plt.ylabel("Close Price USD($)")
plt.legend(loc='upper left')
plt.show

#CODE CREDIT : Computer Science
# RECREATED  With Real time data BY : Eddie-M-Learning

